<?php

declare(strict_types=1);

/** @var  \Aheadworks\Rbslider\Block\Banner  $block */
/** @var \Magento\Framework\Escaper $escaper */

?> 

<script>
    'use strict';
    function initAwRbslider(config){
        return {
        options: Object.assign({
            autoplay: true,
            pauseTimeBetweenTransitions: 3000,
            slideTransitionSpeed: 500,
            isStopAnimationMouseOnBanner: true,
            animation: 'fade',
            isRandomOrderImage: false,
            sliderListSelector: '.uk-slideshow',
            sliderItemSelector: '.aw-rbslider-item'
        },config),

        slideshow:{options:{}},

        /**
         * Initialize widget
         */
        initSlider() {

            /*if (this.options.isRandomOrderImage) {
                this._randomSort();
            }*/

            // UIkit.on('init.uk.component', (e, name, data)=> {
            //     if (name == 'slideshow') {
            //         this.loadSlides(data);
            //     }
            // });
            // window.addEventListener('init.uk.component',(e,name,data)=>{
            //     if (name == 'slideshow') {
            //         this.loadSlides(data);
            //     }
            // })

            this.slideshow = window.awRbslider(this.$el, {
                autoplay: this.options.autoplay,
                autoplayInterval: this.options.pauseTimeBetweenTransitions,
                duration: this.options.slideTransitionSpeed,
                pauseOnHover: this.options.isStopAnimationMouseOnBanner,
                animation: this.options.animation
            });

            this.loadSlides();

            // Rewrite slideshow resize method
            this.slideshow.resize =  () => this.resizeBanner(this.slideshow,this.$el);

            // Disable stop animation, if click on slide navigation or dot navigation
            // this.element.on('click.uk.slideshow', '[data-uk-slideshow-item]', function(e) {
            //     if (this.slideshow.options.autoplay) {
            //         this.slideshow.start();
            //     }
            // });


            // Array.from(this.$el.querySelectorAll('data-uk-slideshow-item')).map(item => {
            //     item.addEventListener('click.uk.slideshow',(e)=>{
            //         if (slideshow.options.autoplay) {
            //             slideshow.start();
            //         }
            //     })
            // })

            // Slideshow paused, if mouse cursor on slide navigation or dot navigation
            // this.element.on({
            //     mouseenter: function() {
            //         if (slideshow.options.pauseOnHover) {
            //             slideshow.hovering = true;
            //         }
            //     },
            //     mouseleave: function() {
            //         slideshow.hovering = false;
            //     }
            // }, '.uk-dotnav, .uk-slidenav');

            // this.loadSlider();
            // const observer = new IntersectionObserver(entries=>{
            //     if(entries[0].isIntersecting){
            //         this.loadSlider();
            //         observer.disconnect();
            //     }
            // })
            // observer.observe(this.$el);

            if (this.options.bannerSchedule.length > 0) {
                if (!this.timeValidator([this.options.bannerSchedule[0]])) {
                    this.delayedUpdate(this.options.bannerSchedule[0]);
                }
                if (this.timeValidator(this.options.bannerSchedule)) {
                    this.sendRequest(this.options.bannerId);
                }
            }

            // window.loadSlider = () => this.loadSlider();

        },

        loadSlider(){
            // console.log("hello from loadSlider");
            if(!window.awRbslider){
                let callbacks=[];
                // console.log("just hello");
                window.awRbslider = {'-isLoading': () => callbacks.push(() => this.loadSlider())}; 
                    const script = document.createElement('script');
                    script.src = '<?= $escaper->escapeJs($block->getViewFileUrl('Compat_Aheadworks/js/components/slideshow.js')) ?>';
                    script.onload = () => {
                        callbacks.map(callback => callback());
                        callbacks=[];
                    };

                    document.head.append(script);
                }
                
                if(window.awRbslider['-isLoading']){
                   window.awRbslider['-isLoading'](()=>this.loadSlider());

                }
                
                if(!window.awRbslider['-isLoading']){
                    console.log('instantiate slider here');
                    this.initSlider();
                }
        },

        pauseOnEnter(){
            if(this.slideshow.options.pauseOnHover){
                this.slideshow.hovering=true;
            }
        },

        resumeOnLeave(){
            this.slideshow.hovering=false;
        },

        /**
         * Recalculate the width and height of the banner
         */
        resizeBanner(slideshow, componentRoot) {
            const mainContent = componentRoot.closest('#maincontent, .page-wrapper');
                let width,
                height = slideshow.options.height;

            // Recalculate width
            if (slideshow.slides.length) {
                width = slideshow.slides[0].querySelector('img.aw-rbslider__img').naturalWidth;
            }
            if (mainContent) {
                if (mainContent.getBoundingClientRect().width < width) {
                    width = mainContent.getBoundingClientRect().width;
                }
                componentRoot.style.width = width+'px';
            } 
            // else if (document.querySelector('.page-wrapper')) {
            //     // AW RBSlider compatibility
            //     const containerWidth = Math.floor(document.querySelector('.page-wrapper').getBoundingClientRect().width * 0.7);

            //     if (containerWidth < width) {
            //         width = containerWidth;
            //     }
            //     componentRoot.style.width = width+'px';
            // }
            // Recalculate height
            if (slideshow.options.height === 'auto' && slideshow.slides.length) {
                slideshow.slides[0].style.height =  '';
                height = slideshow.slides[0].getBoundingClientRect().height;
                slideshow.container.style.height =  height+'px';
                slideshow.slides.map(slide=>{
                    slide.style.height = height+'px';
                    slide.style.position = 'absolute';
                })
                // slideshow.slides.css('height', height);
                // slideshow.slides.css('position', 'absolute');
            }
        },

        /**
         * Lazy load slides
         */
        loadSlides() {
            // let slideImg;

            this.slideshow.slides.forEach((slideElem,index)=> {
                if (index) {
                    const slideImg = slideElem.querySelector('img.aw-rbslider__img');
                    if (slideImg && slideImg.dataset.src) {
                        slideImg.addEventListener('load',() => slideImg.classList.add('is-loaded'));
                        // slideImg.on('load', function () {
                        //     $(this).addClass('is-loaded');
                        // });

                        slideImg.src = slideImg.dataset.src;

                        // slideImg.prop('src', slideImg.attr('data-src'));
                        slideImg.removeAttribute('data-src');
                        
                        // slideImg.attr('data-src', null);
                    }
                }
            });
        },

        
        timeValidator(schedule) {
            // var currentDate = moment().utc().format('YYYY-MM-DD HH:mm'),
            const currentDateMinute = Date.now()/1000/60;

            let isValid = false;
            schedule.forEach(item => {
                if (currentDateMinute === new Date(item).getTime()/1000/60) {
                    isValid = true;
                }
            });

            return isValid;
        },

        /**
         * Send request for clean banner cache
         *
         * @param bannerId
         */

        // $.ajax({
            //     url: this.options.cacheCleanUrl,
            //     type: 'post',
            //     async: true,
            //     dataType: 'json',
            //     data: {
            //         'bannerId': bannerId
            //     }
            // });
        sendRequest(bannerId) {
            fetch(this.options.cacheCleanUrl,{
                method:'post',
                headers:{contentType:'application/json'},
                body:JSON.stringify({bannerId})
            }); 
        },

        /**
         * Calculate time before send ajax request
         *
         * @param futureTime
         */
        delayedUpdate(futureTime) {

            // var currentDate = moment().utc().format('YYYY-MM-DD HH:mm'),
            const currentDateMinute = Math.floor(Date.now()/1000/60);

            // interval =  moment(moment(futureTime,"YYYY-MM-DD HH:mm").diff(moment(currentDateMinute,"YYYY-MM-DD HH:mm")));
            const interval = Math.floor(new Date(futureTime).getTime()/1000/60) - currentDateMinute;
            if (interval > 0) {
                setTimeout(()  => this.sendRequest(self.options.bannerId), interval);
            }
        },

        /**
         * Random sort
         * @private
         */
        _randomSort: function () {
            const sliderListSelector = this.options.sliderListSelector,
                sliderItemSelector = this.options.sliderItemSelector;

            this.$el.querySelector(sliderListSelector)
                // .html($(this.element).find(sliderListSelector + ' ' + sliderItemSelector).sort(function(){
                //     return Math.random()-0.5;
                // }));
                .innerHTML = Array.from(this.$el.querySelectorAll(sliderListSelector+' '+sliderItemSelector))
                .sort(() => Math.random() - 0.5)
                .map(item => item.outerHTML)
                .join('');
        }
    };
    }
</script>


<?php if ($bannersBlock = $block->getBlocks()): ?>
    <?php foreach ($bannersBlock as $bannerBlock): ?>
        <?php
            $dotNavItems = '';
            $slideCounter = 1;
            $sliderConfig = $block->getBannerMageInitParams($bannerBlock)['awRbslider'];
        ?>

        <div 
             x-data='initAwRbslider(<?= /* @noEscape */ $block->jsonEncode($sliderConfig) ?>)'
             x-intersect="loadSlider()"
             data-aw-rbslider-banner-id='<?= /* @noEscape */ $bannerBlock->getBanner()->getId(); ?>'
             class="aw-rbslider-container uk-slidenav-position">
            <div class="uk-slideshow uk-overlay-active">
                <?php foreach ($bannerBlock->getSlides() as $key => $slide): ?>
                    <div class="aw-rbslider-item">
                        <div class="aw-rbslider-img-wrapper">
                            <picture>
                                <source media="(max-width: 480px)" srcset="<?= /* @noEscape */ $block->getSlideMobileImgUrl($slide) ?>"
                                        class="aw-rbslider__img  <?= $slideCounter === 1 ? 'is-loaded' : '' ?>"
                                        <?= $slideCounter !== 1 ? 'data-' : '' ?>
                                        title="<?= $escaper->escapeHtml($slide->getImgTitle()) ?>" />
                                <img class="aw-rbslider__img  <?= $slideCounter === 1 ? 'is-loaded' : '' ?>"
                                     <?= $slideCounter !== 1 ? 'data-' : '' ?>src="<?= /* @noEscape */ $block->getSlideImgUrl($slide) ?>"
                                     title="<?= $escaper->escapeHtml($slide->getImgTitle()) ?>"
                                     alt="<?= $escaper->escapeHtml($slide->getImgAlt()) ?>" />
                            </picture>
                            <?php if ($slide->getUrl()): ?>
                                <?php
                                    $target = $slide->getIsOpenUrlInNewWindow() ? 'target="_blank"' : '';
                                    $nofollow = $slide->getIsAddNofollowToUrl() ? 'rel="nofollow"' : '';
                                ?>
                                <a href="<?= /* @noEscape */ $slide->getUrl() ?>"
                                   class="aw-rbslider-img-url"
                                   data-mage-init='<?= /* @noEscape */ $block->jsonEncode($block->getSendClickStatisticsMageInitParams($bannerBlock->getBanner(), $slide)) ?>'
                                    <?= /* @noEscape */ $target ?>
                                    <?= /* @noEscape */ $nofollow ?>></a>
                            <?php endif; ?>
                            <?php if ($content = $slide->getContent()): ?>
                                <div class="aw-rbslider-content-wrapper uk-overlay-panel uk-flex uk-flex-center uk-flex-middle uk-text-center">
                                    <div>
                                        <?= /* @noEscape */ $content ?>
                                    </div>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                    <?php $dotNavItems .= '<li data-uk-slideshow-item="' . $key . '" 
                                            @click.prevent = "slideshow.show(' . $key . ')"
                                        ><a href="#"></a></li>' ?>
                    <?php $slideCounter++; ?>
                <?php endforeach; ?>
            </div>
            <?php if (count($bannerBlock->getSlides()) > 1): ?>
                <?php if ($bannerBlock->getBanner()->getDisplayArrows()): ?>
                    <a href="#"
                       class="uk-slidenav uk-slidenav-contrast uk-slidenav-previous"
                       @mouseenter="pauseOnEnter"
                       @mouseleave="resumeOnLeave"
                       @click.prevent = "slideshow.previous()"
                       data-uk-slideshow-item="previous">
                        <span class="visually-hidden"><?= $escaper->escapeHtml(__('Show previous slide')) ?></span>
                    </a>
                    <a href="#"
                       class="uk-slidenav uk-slidenav-contrast uk-slidenav-next"
                       @mouseenter="pauseOnEnter"
                       @mouseleave="resumeOnLeave"
                       @click.prevent = "slideshow.next()"
                       data-uk-slideshow-item="next">
                        <span class="visually-hidden"><?= $escaper->escapeHtml(__('Show next slide')) ?></span>
                    </a>
                <?php endif; ?>
                <?php if ($bannerBlock->getBanner()->getDisplayBullets()): ?>
                    <ul class="uk-dotnav uk-dotnav-contrast uk-position-bottom uk-flex-center"
                       @mouseenter="pauseOnEnter"
                       @mouseleave="resumeOnLeave"
                    >
                        <?= /* @noEscape */  $dotNavItems ?>
                    </ul>
                <?php endif; ?>
            <?php endif; ?>
        </div>
    <?php endforeach; ?>
<?php endif; ?>


<div class="text-blue-300 lg:bg-[#560088] w-2 font-bold h-20 text-4xl">
    <!-- <h5 class="p-3 text-red-400">hello world</h5> -->
</div>