<?php
// @codingStandardsIgnoreFile

/** @var $block \Aheadworks\Rbslider\Block\Banner */

?>
<?php if ($bannersBlock = $block->getBlocks()): ?>
    <?php foreach ($bannersBlock as $bannerBlock) : ?>
        <?php
            $dotNavItems = '';
            $slideCounter = 1;
        ?>
        <div data-mage-init='<?= /* @noEscape */ $block->jsonEncode($block->getBannerMageInitParams($bannerBlock)) ?>'
             data-aw-rbslider-banner-id='<?= /* @noEscape */ $bannerBlock->getBanner()->getId(); ?>'
             class="aw-rbslider-container uk-slidenav-position">
            <div class="uk-slideshow uk-overlay-active">
                <?php foreach ($bannerBlock->getSlides() as $key => $slide) : ?>
                    <div class="aw-rbslider-item">
                        <div class="aw-rbslider-img-wrapper">
                            <picture>
                                <source media="(max-width: 480px)" srcset="<?= /* @noEscape */ $block->getSlideMobileImgUrl($slide) ?>"
                                        class="aw-rbslider__img  <?= $slideCounter === 1 ? 'is-loaded' : '' ?>"
                                        <?= $slideCounter !== 1 ? 'data-' : '' ?>
                                        title="<?= $block->escapeHtml($slide->getImgTitle()) ?>" />
                                <img class="aw-rbslider__img  <?= $slideCounter === 1 ? 'is-loaded' : '' ?>"
                                     <?= $slideCounter !== 1 ? 'data-' : '' ?>src="<?= /* @noEscape */ $block->getSlideImgUrl($slide) ?>"
                                     title="<?= $block->escapeHtml($slide->getImgTitle()) ?>"
                                     alt="<?= $block->escapeHtml($slide->getImgAlt()) ?>" />
                            </picture>
                            <?php if ($slide->getUrl()): ?>
                                <?php
                                    $target = $slide->getIsOpenUrlInNewWindow() ? 'target="_blank"' : '';
                                    $nofollow = $slide->getIsAddNofollowToUrl() ? 'rel="nofollow"' : '';
                                ?>
                                <a href="<?= /* @noEscape */ $slide->getUrl() ?>"
                                   class="aw-rbslider-img-url"
                                   data-mage-init='<?= /* @noEscape */ $block->jsonEncode($block->getSendClickStatisticsMageInitParams($bannerBlock->getBanner(), $slide)) ?>'
                                    <?= /* @noEscape */ $target ?>
                                    <?= /* @noEscape */ $nofollow ?>></a>
                            <?php endif; ?>
                            <?php if ($content = $slide->getContent()): ?>
                                <div class="aw-rbslider-content-wrapper uk-overlay-panel uk-flex uk-flex-center uk-flex-middle uk-text-center">
                                    <div>
                                        <?= /* @noEscape */ $content ?>
                                    </div>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                    <?php $dotNavItems .= '<li data-uk-slideshow-item="' . $key . '"><a href="#"></a></li>' ?>
                    <?php $slideCounter++; ?>
                <?php endforeach; ?>
            </div>
            <?php if (count($bannerBlock->getSlides()) > 1): ?>
                <?php if ($bannerBlock->getBanner()->getDisplayArrows()) : ?>
                    <a href="#"
                       class="uk-slidenav uk-slidenav-contrast uk-slidenav-previous"
                       data-uk-slideshow-item="previous">
                        <span class="visually-hidden"><?= $block->escapeHtml(__('Show previous slide')) ?></span>
                    </a>
                    <a href="#"
                       class="uk-slidenav uk-slidenav-contrast uk-slidenav-next"
                       data-uk-slideshow-item="next">
                        <span class="visually-hidden"><?= $block->escapeHtml(__('Show next slide')) ?></span>
                    </a>
                <?php endif; ?>
                <?php if ($bannerBlock->getBanner()->getDisplayBullets()) : ?>
                    <ul class="uk-dotnav uk-dotnav-contrast uk-position-bottom uk-flex-center">
                        <?= /* @noEscape */  $dotNavItems ?>
                    </ul>
                <?php endif; ?>
            <?php endif; ?>
        </div>
    <?php endforeach; ?>
<?php endif; ?>
